//! TOSEC category mapping - maps DAT name prefixes to category paths
//!
//! This mapping is derived from the official TOSEC move scripts.
//! Last updated: TOSEC-v2025-03-13

use phf::phf_map;

/// Maps TOSEC DAT name prefixes to category path prefixes
/// e.g., "Commodore Amiga" -> "Commodore/Amiga"
pub static TOSEC_PREFIX_MAP: phf::Map<&'static str, &'static str> = phf_map! {

    "8-Bit Productions Commander X16" => "8-Bit Productions/Commander X16",
    "ACT Apricot PC-Xi" => "ACT/Apricot PC-Xi",
    "AEG Olympia Olytext 20" => "AEG/Olympia Olytext 20",
    "AMPRO Computers LittleBoard Z80" => "AMPRO Computers/LittleBoard Z80",
    "APF Imagination Machine" => "APF/Imagination Machine",
    "APF M-1000" => "APF/M-1000",
    "AT&T 3B20" => "AT&T/3B20",
    "Acorn Archimedes" => "Acorn/Archimedes",
    "Acorn Atom" => "Acorn/Atom",
    "Acorn BBC" => "Acorn/BBC",
    "Acorn BBC Master" => "Acorn/BBC Master",
    "Acorn Electron" => "Acorn/Electron",
    "Acorn FileStore E01" => "Acorn/FileStore E01",
    "Acorn Risc PC" => "Acorn/Risc PC",
    "Acorn System Series" => "Acorn/System Series",
    "Advanced Computer Design PDQ-3" => "Advanced Computer Design/PDQ-3",
    "AlphaSmart Pro" => "AlphaSmart/Pro",
    "Alspa Computers ALSPA" => "Alspa Computers/ALSPA",
    "Altos Computer Systems ACS-186, 586, 686 & 986" => "Altos Computer Systems/ACS-186, 586, 686 & 986",
    "Altos Computer Systems ACS-8000" => "Altos Computer Systems/ACS-8000",
    "Altos Computer Systems ACS-8600" => "Altos Computer Systems/ACS-8600",
    "Altos Computer Systems Series 5" => "Altos Computer Systems/Series 5",
    "Amstrad CPC" => "Amstrad/CPC",
    "Amstrad GX4000" => "Amstrad/GX4000",
    "Amstrad NC-100" => "Amstrad/NC-100",
    "Amstrad NC-200" => "Amstrad/NC-200",
    "Amstrad PCW" => "Amstrad/PCW",
    "Analogue Mega Sg" => "Analogue/Mega Sg",
    "Analogue Nt" => "Analogue/Nt",
    "Analogue Nt Mini" => "Analogue/Nt Mini",
    "Analogue Nt Mini Noir" => "Analogue/Nt Mini Noir",
    "Analogue Pocket" => "Analogue/Pocket",
    "Analogue Super Nt" => "Analogue/Super Nt",
    "Apollo Apollo-Domain Workstations" => "Apollo/Apollo-Domain Workstations",
    "Apple 1" => "Apple/1",
    "Apple II" => "Apple/II",
    "Apple IIGS" => "Apple/IIGS",
    "Apple III" => "Apple/III",
    "Apple Lisa" => "Apple/Lisa",
    "Apple Macintosh" => "Apple/Macintosh",
    "Applied Technology MicroBee" => "Applied Technology/MicroBee",
    "Aquaplus P-ECE" => "Aquaplus/P-ECE",
    "Arduboy Arduboy" => "Arduboy/Arduboy",
    "Atari 2600 & VCS" => "Atari/2600 & VCS",
    "Atari 5200" => "Atari/5200",
    "Atari 7800" => "Atari/7800",
    "Atari 8bit" => "Atari/8bit",
    "Atari Falcon030" => "Atari/Falcon030",
    "Atari Jaguar" => "Atari/Jaguar",
    "Atari Lynx" => "Atari/Lynx",
    "Atari ST" => "Atari/ST",
    "BGR Computers Excalibur 64" => "BGR Computers/Excalibur 64",
    "Bally Professional Arcade & Astrocade" => "Bally/Professional Arcade & Astrocade",
    "Bandai Design Master Denshi Mangajuku" => "Bandai/Design Master Denshi Mangajuku",
    "Bandai Gundam RX-78" => "Bandai/Gundam RX-78",
    "Bandai Super Vision 8000" => "Bandai/Super Vision 8000",
    "Bandai WonderSwan" => "Bandai/WonderSwan",
    "Bandai WonderSwan Color" => "Bandai/WonderSwan Color",
    "Benesse Pocket Challenge V2" => "Benesse/Pocket Challenge V2",
    "Benesse Pocket Challenge W" => "Benesse/Pocket Challenge W",
    "Bernd Huebler & Klaus-Peter Evert Huebler-Evert-MC" => "Bernd Huebler & Klaus-Peter Evert/Huebler-Evert-MC",
    "Bernd Huebler Huebler-Grafik-MC" => "Bernd Huebler/Huebler-Grafik-MC",
    "Big Mess o'Wires ADB-USB Wombat" => "Big Mess o'Wires/ADB-USB Wombat",
    "Big Mess o'Wires Floppy Emu" => "Big Mess o'Wires/Floppy Emu",
    "Birkbeck College All-Purpose Electronic X-ray Computer" => "Birkbeck College/All-Purpose Electronic X-ray Computer",
    "Bit Corporation BIT 90" => "Bit Corporation/BIT 90",
    "Bit Corporation Gamate" => "Bit Corporation/Gamate",
    "Bondwell 12" => "Bondwell/12",
    "Bondwell 14" => "Bondwell/14",
    "Bondwell 2" => "Bondwell/2",
    "Brother LW-30" => "Brother/LW-30",
    "Brother Super PowerNote PN-8510MDS" => "Brother/Super PowerNote PN-8510MDS",
    "Brother Super PowerNote PN-8800FXB" => "Brother/Super PowerNote PN-8800FXB",
    "Brother Super PowerNote PN8500MDS" => "Brother/Super PowerNote PN8500MDS",
    "Brother WP-1" => "Brother/WP-1",
    "Brother WP-230B, 330MDS & 335B" => "Brother/WP-230B, 330MDS & 335B",
    "Brother WP-2450DS" => "Brother/WP-2450DS",
    "Burroughs B1000 Series" => "Burroughs/B1000 Series",
    "Burroughs B20" => "Burroughs/B20",
    "CCE MC-1000" => "CCE/MC-1000",
    "COMX COMX-35" => "COMX/COMX-35",
    "Cambridge Computer Z88" => "Cambridge Computer/Z88",
    "Camputers Lynx" => "Camputers/Lynx",
    "Casio CFX-9850" => "Casio/CFX-9850",
    "Casio FP-1000 & FP-1100" => "Casio/FP-1000 & FP-1100",
    "Casio Graph 35+" => "Casio/Graph 35+",
    "Casio Loopy" => "Casio/Loopy",
    "Casio PB-100" => "Casio/PB-100",
    "Casio PB-1000" => "Casio/PB-1000",
    "Casio PV-1000" => "Casio/PV-1000",
    "Casio PV-2000" => "Casio/PV-2000",
    "CircuitMess Nibble" => "CircuitMess/Nibble",
    "Coleco ColecoVision" => "Coleco/ColecoVision",
    "Coleco ColecoVision ADAM" => "Coleco/ColecoVision ADAM",
    "Commodore Amiga" => "Commodore/Amiga",
    "Commodore BX256-80HP" => "Commodore/BX256-80HP",
    "Commodore C128" => "Commodore/C128",
    "Commodore C16, C116 & Plus-4" => "Commodore/C16, C116 & Plus-4",
    "Commodore C64" => "Commodore/C64",
    "Commodore C64DTV" => "Commodore/C64DTV",
    "Commodore C65" => "Commodore/C65",
    "Commodore MAX Machine & VIC10" => "Commodore/MAX Machine & VIC10",
    "Commodore PET" => "Commodore/PET",
    "Commodore VIC20" => "Commodore/VIC20",
    "Compugraphic MCS-10" => "Compugraphic/MCS-10",
    "Control Data Corporation CDC110" => "Control Data Corporation/CDC110",
    "Convergent Technologies AWS NGEN Workstation" => "Convergent Technologies/AWS NGEN Workstation",
    "Convergent Technologies MiniFrame" => "Convergent Technologies/MiniFrame",
    "Creatronic Mega Duck & Cougar Boy" => "Creatronic/Mega Duck & Cougar Boy",
    "Cromemco System V" => "Cromemco/System V",
    "Cybiko Cybiko" => "Cybiko/Cybiko",
    "Cybiko Xtreme" => "Cybiko/Xtreme",
    "DEC AlphaServer" => "DEC/AlphaServer",
    "DEC DECPx AXP 150" => "DEC/DECPx AXP 150",
    "DEC PDP-1" => "DEC/PDP-1",
    "DEC PDP-10" => "DEC/PDP-10",
    "DEC PDP-11" => "DEC/PDP-11",
    "DEC PDP-12" => "DEC/PDP-12",
    "DEC PDP-15" => "DEC/PDP-15",
    "DEC PDP-7" => "DEC/PDP-7",
    "DEC PDP-8" => "DEC/PDP-8",
    "DEC PDP-9" => "DEC/PDP-9",
    "DEC Rainbow 100" => "DEC/Rainbow 100",
    "DEC VT-180" => "DEC/VT-180",
    "Data Applications International DAI Personal Computer" => "Data Applications International/DAI Personal Computer",
    "Datapoint Distributed Processors" => "Datapoint/Distributed Processors",
    "Dick Smith Super-80, Super-80D, Super-80E & Super-80M" => "Dick Smith/Super-80, Super-80D, Super-80E & Super-80M",
    "Dick Smith Super-80R & Super-80V" => "Dick Smith/Super-80R & Super-80V",
    "Didact Esselte 100" => "Didact/Esselte 100",
    "Digital Electronics DIGIAC 3080" => "Digital Electronics/DIGIAC 3080",
    "Dragon Data Dragon" => "Dragon Data/Dragon",
    "Dragon Data Dragon Alpha" => "Dragon Data/Dragon Alpha",
    "Dragon Data Dragon Beta" => "Dragon Data/Dragon Beta",
    "Dual Systems 83-20" => "Dual Systems/83-20",
    "Dual Systems 83-80" => "Dual Systems/83-80",
    "Dynabyte Monarch" => "Dynabyte/Monarch",
    "EACA EG2000 Colour Genie" => "EACA/EG2000 Colour Genie",
    "ETL Mark II" => "ETL/Mark II",
    "ETL Mark IV" => "ETL/Mark IV",
    "ETL Mark IV A" => "ETL/Mark IV A",
    "Electronics Australia EDUC-8" => "Electronics Australia/EDUC-8",
    "Elektronika BK-0010-0011M" => "Elektronika/BK-0010-0011M",
    "Elektronika BK-0011-411" => "Elektronika/BK-0011-411",
    "Elektronska Industrija Nis PECOM 32 & 64" => "Elektronska Industrija Nis/PECOM 32 & 64",
    "Emerson Arcadia 2001" => "Emerson/Arcadia 2001",
    "Enterprise 64 & 128" => "Enterprise/64 & 128",
    "Entex Adventure Vision" => "Entex/Adventure Vision",
    "Epoch Super Cassette Vision" => "Epoch/Super Cassette Vision",
    "Epson PX-4 & HC-40" => "Epson/PX-4 & HC-40",
    "Epson PX-8, HC-88 & Geneva" => "Epson/PX-8, HC-88 & Geneva",
    "Epson QX-10" => "Epson/QX-10",
    "Ericsson Alfaskop System 41" => "Ericsson/Alfaskop System 41",
    "Exelvision EXL100" => "Exelvision/EXL100",
    "Exelvision Exeltel" => "Exelvision/Exeltel",
    "Exidy Sorcerer" => "Exidy/Sorcerer",
    "Fairchild VES & Channel F" => "Fairchild/VES & Channel F",
    "Fairlight CMI Series III" => "Fairlight/CMI Series III",
    "Ferguson Big Board II" => "Ferguson/Big Board II",
    "Fidelity Sensory Chess Challenger" => "Fidelity/Sensory Chess Challenger",
    "Flexible Systems Tasman Turtle" => "Flexible Systems/Tasman Turtle",
    "Front Fareast Magic Drive" => "Front Fareast/Magic Drive",
    "Fuji Photo Film FUJIC" => "Fuji Photo Film/FUJIC",
    "Fujitsu FM R-50" => "Fujitsu/FM R-50",
    "Fujitsu FM Towns" => "Fujitsu/FM Towns",
    "Fujitsu FM-7" => "Fujitsu/FM-7",
    "Fujitsu FM77-AV" => "Fujitsu/FM77-AV",
    "Fukutake Publishing StudyBox" => "Fukutake Publishing/StudyBox",
    "Funtech Super A'can" => "Funtech/Super A'can",
    "GCE Vectrex" => "GCE/Vectrex",
    "Gakken Compact Vision TV Boy" => "Gakken/Compact Vision TV Boy",
    "Galaksija Galaksija" => "Galaksija/Galaksija",
    "Galaksija Galaksija Plus" => "Galaksija/Galaksija Plus",
    "Game Park GP32" => "Game Park/GP32",
    "Gamebuino META" => "Gamebuino/META",
    "Gould K105-D Logic Analyzer" => "Gould/K105-D Logic Analyzer",
    "Gould K115 Logic Analyzer" => "Gould/K115 Logic Analyzer",
    "Gould K450 Logic Analyzer" => "Gould/K450 Logic Analyzer",
    "Grundy NewBrain" => "Grundy/NewBrain",
    "Hanimex Pencil II" => "Hanimex/Pencil II",
    "Hartung Game Master" => "Hartung/Game Master",
    "Hawthorne Technology TinyGiant 68000 Single Board Computer" => "Hawthorne Technology/TinyGiant 68000 Single Board Computer",
    "Hector 2HR" => "Hector/2HR",
    "Hewlett-Packard 16500A" => "Hewlett-Packard/16500A",
    "Hewlett-Packard 4951C & 4952A" => "Hewlett-Packard/4951C & 4952A",
    "Hewlett-Packard HP 64000 Logic Development System" => "Hewlett-Packard/HP 64000 Logic Development System",
    "Hewlett-Packard HP48" => "Hewlett-Packard/HP48",
    "Hewlett-Packard HP49" => "Hewlett-Packard/HP49",
    "Hewlett-Packard HP85" => "Hewlett-Packard/HP85",
    "Hewlett-Packard HP9835A-B" => "Hewlett-Packard/HP9835A-B",
    "Hewlett-Packard LaserJet" => "Hewlett-Packard/LaserJet",
    "Hitachi Basic Master Jr." => "Hitachi/Basic Master Jr.",
    "Hitachi Basic Master Jr. Level 2" => "Hitachi/Basic Master Jr. Level 2",
    "Hitachi Basic Master Jr. Level 3" => "Hitachi/Basic Master Jr. Level 3",
    "Hitachi S1" => "Hitachi/S1",
    "HomeLab BraiLab" => "HomeLab/BraiLab",
    "HomeLab HomeLab" => "HomeLab/HomeLab",
    "IBM 1620" => "IBM/1620",
    "IBM 3270" => "IBM/3270",
    "IBM 3740" => "IBM/3740",
    "IBM Displaywriter" => "IBM/Displaywriter",
    "IBM PC Compatibles" => "IBM/PC Compatibles",
    "IBM PCjr" => "IBM/PCjr",
    "IBM System-36" => "IBM/System-36",
    "IBM System-360" => "IBM/System-360",
    "IMLAC Corporation PDS-1" => "IMLAC Corporation/PDS-1",
    "Infocom Z-Machine" => "Infocom/Z-Machine",
    "Intec Interact" => "Intec/Interact",
    "Interact Family Computer" => "Interact/Family Computer",
    "John L. Weinrich 4004 Nixie Clock" => "John L. Weinrich/4004 Nixie Clock",
    "Jupiter Cantab Jupiter Ace" => "Jupiter Cantab/Jupiter Ace",
    "Kaypro II" => "Kaypro/II",
    "Keio University K-1" => "Keio University/K-1",
    "Lambda Electronics Lambda 8300" => "Lambda Electronics/Lambda 8300",
    "LeapFrog LeapPad" => "LeapFrog/LeapPad",
    "LeapFrog Leapster" => "LeapFrog/Leapster",
    "Leonardo Miliani LM80C Color Computer" => "Leonardo Miliani/LM80C Color Computer",
    "Librascope LGP-30" => "Librascope/LGP-30",
    "Luxor ABC 1600" => "Luxor/ABC 1600",
    "Luxor ABC 80" => "Luxor/ABC 80",
    "Luxor ABC 800" => "Luxor/ABC 800",
    "Luxor ABC 806" => "Luxor/ABC 806",
    "Luxor ABC 832" => "Luxor/ABC 832",
    "Luxor Video Entertainment System" => "Luxor/Video Entertainment System",
    "MEGA MEGA65" => "MEGA/MEGA65",
    "MGT Sam Coupe" => "MGT/Sam Coupe",
    "MITS Altair 8800" => "MITS/Altair 8800",
    "MSX MSX" => "MSX/MSX",
    "MSX MSX2" => "MSX/MSX2",
    "MSX MSX2+" => "MSX/MSX2+",
    "MSX TurboR" => "MSX/TurboR",
    "Magnavox Odyssey2" => "Magnavox/Odyssey2",
    "Manfred Kramer Kramer-MC" => "Manfred Kramer/Kramer-MC",
    "Matra Hachette Alice 32" => "Matra Hachette/Alice 32",
    "Matra Hachette Alice 90" => "Matra Hachette/Alice 90",
    "Matsushita JR-100" => "Matsushita/JR-100",
    "Matsushita JR-200" => "Matsushita/JR-200",
    "Mattel Aquarius" => "Mattel/Aquarius",
    "Mattel Intellivision" => "Mattel/Intellivision",
    "Mattel Intellivision ECS" => "Mattel/Intellivision ECS",
    "Mattel Juice Box" => "Mattel/Juice Box",
    "Megatel Quark" => "Megatel/Quark",
    "Memotech MTX" => "Memotech/MTX",
    "Michael J. Bauer DREAM-6800" => "Michael J. Bauer/DREAM-6800",
    "Micro Craft Dimension 68000" => "Micro Craft/Dimension 68000",
    "Microkey Primo" => "Microkey/Primo",
    "Microsoft Pocket PC" => "Microsoft/Pocket PC",
    "Ministerstvo radiopromy'shlennosti Korvet" => "Ministerstvo radiopromy'shlennosti/Korvet",
    "Mitsubishi Multi 8" => "Mitsubishi/Multi 8",
    "Motorola EXORciser" => "Motorola/EXORciser",
    "Motorola MotoMagx" => "Motorola/MotoMagx",
    "Motorola VME10" => "Motorola/VME10",
    "Mr. Isizu Z80 TV Game System" => "Mr. Isizu/Z80 TV Game System",
    "Multi-format" => "Multi-format/Compilations",
    "NCR Decision Mate V" => "NCR/Decision Mate V",
    "NCR Tower" => "NCR/Tower",
    "NEC Advanced Personal Computer" => "NEC/Advanced Personal Computer",
    "NEC PC-2001" => "NEC/PC-2001",
    "NEC PC-6001" => "NEC/PC-6001",
    "NEC PC-8001" => "NEC/PC-8001",
    "NEC PC-8201" => "NEC/PC-8201",
    "NEC PC-8801" => "NEC/PC-8801",
    "NEC PC-88VA" => "NEC/PC-88VA",
    "NEC PC-9801" => "NEC/PC-9801",
    "NEC PC-9821" => "NEC/PC-9821",
    "NEC PC-Engine & TurboGrafx-16" => "NEC/PC-Engine & TurboGrafx-16",
    "NEC SuperGrafx" => "NEC/SuperGrafx",
    "Nascom I & II" => "Nascom/I & II",
    "Nichibutsu My Vision" => "Nichibutsu/My Vision",
    "Nikko digiBLAST Portable" => "Nikko/digiBLAST Portable",
    "Nintendo 3DS" => "Nintendo/3DS",
    "Nintendo 64" => "Nintendo/64",
    "Nintendo 64DD" => "Nintendo/64DD",
    "Nintendo DS" => "Nintendo/DS",
    "Nintendo DSi" => "Nintendo/DSi",
    "Nintendo Famicom & Entertainment System" => "Nintendo/Famicom & Entertainment System",
    "Nintendo Famicom Disk System" => "Nintendo/Famicom Disk System",
    "Nintendo Family BASIC" => "Nintendo/Family BASIC",
    "Nintendo Game Boy" => "Nintendo/Game Boy",
    "Nintendo Game Boy Advance" => "Nintendo/Game Boy Advance",
    "Nintendo Game Boy Color" => "Nintendo/Game Boy Color",
    "Nintendo GameCube" => "Nintendo/GameCube",
    "Nintendo Play-Yan" => "Nintendo/Play-Yan",
    "Nintendo Pokemon Mini" => "Nintendo/Pokemon Mini",
    "Nintendo Pokewalker" => "Nintendo/Pokewalker",
    "Nintendo Sufami Turbo" => "Nintendo/Sufami Turbo",
    "Nintendo Super Famicom & Super Entertainment System" => "Nintendo/Super Famicom & Super Entertainment System",
    "Nintendo Virtual Boy" => "Nintendo/Virtual Boy",
    "Nintendo Wii" => "Nintendo/Wii",
    "Nokia N-Gage" => "Nokia/N-Gage",
    "Nokia N900" => "Nokia/N900",
    "NorthStar Advantage" => "NorthStar/Advantage",
    "NorthStar Horizon" => "NorthStar/Horizon",
    "Nuclear Data ND4410 & ND4420" => "Nuclear Data/ND4410 & ND4420",
    "OCC Osborne 1 & Osborne Executive" => "OCC/Osborne 1 & Osborne Executive",
    "Oh! MZ S-OS" => "Oh! MZ/S-OS",
    "Ohio Scientific Challenger 1P" => "Ohio Scientific/Challenger 1P",
    "Olimex Neo6502" => "Olimex/Neo6502",
    "Olivetti M20" => "Olivetti/M20",
    "OpenPandora Pandora" => "OpenPandora/Pandora",
    "Otrona Attache" => "Otrona/Attache",
    "PEL Varazdin Orao" => "PEL Varazdin/Orao",
    "PTC Sol Terminal Computer SOL-20" => "PTC/Sol Terminal Computer SOL-20",
    "Panic Playdate" => "Panic/Playdate",
    "Patisonic Aleste 520EX" => "Patisonic/Aleste 520EX",
    "Peters Plus Sprinter" => "Peters Plus/Sprinter",
    "Philips P2000" => "Philips/P2000",
    "Philips VG 5000" => "Philips/VG 5000",
    "Philips Videopac+" => "Philips/Videopac+",
    "Pimoroni 32blit" => "Pimoroni/32blit",
    "Pimoroni PicoSystem" => "Pimoroni/PicoSystem",
    "Pioneer LaserActive" => "Pioneer/LaserActive",
    "Pokitto Oy Pokitto" => "Pokitto Oy/Pokitto",
    "Pravetz 8D" => "Pravetz/8D",
    "Psion Series 5" => "Psion/Series 5",
    "RCA Chip-8" => "RCA/Chip-8",
    "RCA Microboard Computer Development System" => "RCA/Microboard Computer Development System",
    "RCA Studio II" => "RCA/Studio II",
    "RCA Superchip" => "RCA/Superchip",
    "RM Nimbus PC" => "RM/Nimbus PC",
    "Radica Arcade Legends & Play TV Legends" => "Radica/Arcade Legends & Play TV Legends",
    "Radio-86RK Apogej BK-01" => "Radio-86RK/Apogej BK-01",
    "Radio-86RK Mikro-80" => "Radio-86RK/Mikro-80",
    "Radio-86RK Mikrosha" => "Radio-86RK/Mikrosha",
    "Radio-86RK Partner-01.01" => "Radio-86RK/Partner-01.01",
    "Radio-86RK Radio-86RK" => "Radio-86RK/Radio-86RK",
    "Radio-86RK YuT-88" => "Radio-86RK/YuT-88",
    "Raytheon 704" => "Raytheon/704",
    "Raytheon Apollo Guidance Computer" => "Raytheon/Apollo Guidance Computer",
    "Regnecentralen RC 700" => "Regnecentralen/RC 700",
    "Retroleum V6Z80P+" => "Retroleum/V6Z80P+",
    "Robotron A7100, A7150 & K8918" => "Robotron/A7100, A7150 & K8918",
    "Robotron BIC A5105" => "Robotron/BIC A5105",
    "Robotron HC900, KC85 2, KC85 3 & KC85 4" => "Robotron/HC900, KC85 2, KC85 3 & KC85 4",
    "Robotron KC Compact" => "Robotron/KC Compact",
    "Robotron Z1013" => "Robotron/Z1013",
    "Robotron Z9001 & KC85 1" => "Robotron/Z9001 & KC85 1",
    "Rockwell AIM65" => "Rockwell/AIM65",
    "Roland GS Compatibles" => "Roland/GS Compatibles",
    "Roman Sokolov ESPboy" => "Roman Sokolov/ESPboy",
    "SABA Videoplay" => "SABA/Videoplay",
    "SME Systems Aussie Byte II" => "SME Systems/Aussie Byte II",
    "SNK Neo-Geo" => "SNK/Neo-Geo",
    "SNK Neo-Geo CD" => "SNK/Neo-Geo CD",
    "SNK Neo-Geo Pocket" => "SNK/Neo-Geo Pocket",
    "SNK Neo-Geo Pocket Color" => "SNK/Neo-Geo Pocket Color",
    "Samsung SPC-1000" => "Samsung/SPC-1000",
    "Sanyo MBC-550 & 555" => "Sanyo/MBC-550 & 555",
    "Sanyo PHC-25" => "Sanyo/PHC-25",
    "Sega 32X" => "Sega/32X",
    "Sega AI Computer" => "Sega/AI Computer",
    "Sega Advanced Pico Beena" => "Sega/Advanced Pico Beena",
    "Sega Computer 3000" => "Sega/Computer 3000",
    "Sega Game 1000" => "Sega/Game 1000",
    "Sega Game Gear" => "Sega/Game Gear",
    "Sega Mark III & Master System" => "Sega/Mark III & Master System",
    "Sega Mega Drive & Genesis" => "Sega/Mega Drive & Genesis",
    "Sega Mega-CD & Sega CD" => "Sega/Mega-CD & Sega CD",
    "Sega Pico" => "Sega/Pico",
    "Sega Super Control Station" => "Sega/Super Control Station",
    "Sega Visual Memory System" => "Sega/Visual Memory System",
    "Sega WonderMega" => "Sega/WonderMega",
    "Sharp MZ-2000 & MZ-2200" => "Sharp/MZ-2000 & MZ-2200",
    "Sharp MZ-2500" => "Sharp/MZ-2500",
    "Sharp MZ-700" => "Sharp/MZ-700",
    "Sharp MZ-800 & MZ-1500" => "Sharp/MZ-800 & MZ-1500",
    "Sharp MZ-80B" => "Sharp/MZ-80B",
    "Sharp PC-G850, PC-G815 & E200" => "Sharp/PC-G850, PC-G815 & E200",
    "Sharp S-BASIC" => "Sharp/S-BASIC",
    "Sharp Wizard OZ-700 Series" => "Sharp/Wizard OZ-700 Series",
    "Sharp X1" => "Sharp/X1",
    "Sharp X1 Turbo" => "Sharp/X1 Turbo",
    "Sharp X68000" => "Sharp/X68000",
    "Sinclair QL" => "Sinclair/QL",
    "Sinclair ZX Spectrum" => "Sinclair/ZX Spectrum",
    "Sinclair ZX80" => "Sinclair/ZX80",
    "Sinclair ZX81" => "Sinclair/ZX81",
    "Sony PlayStation Vita" => "Sony/PlayStation Vita",
    "Sony PocketStation" => "Sony/PocketStation",
    "Sony SMC-777" => "Sony/SMC-777",
    "Sord M5" => "Sord/M5",
    "Spectravideo SVI-318 & SVI-328" => "Spectravideo/SVI-318 & SVI-328",
    "TRQ Video Computer H-21" => "TRQ/Video Computer H-21",
    "Tandy Radio Shack TRS-80 Color Computer" => "Tandy Radio Shack/TRS-80 Color Computer",
    "Tandy Radio Shack TRS-80 MC-10" => "Tandy Radio Shack/TRS-80 MC-10",
    "Tandy Radio Shack TRS-80 Model 100" => "Tandy Radio Shack/TRS-80 Model 100",
    "Tandy Radio Shack TRS-80 Model 4" => "Tandy Radio Shack/TRS-80 Model 4",
    "Tandy Radio Shack TRS-80 Model I" => "Tandy Radio Shack/TRS-80 Model I",
    "Tandy Radio Shack TRS-80 Model III" => "Tandy Radio Shack/TRS-80 Model III",
    "Tangerine Microtan 65" => "Tangerine/Microtan 65",
    "Tangerine Oric Telestrat" => "Tangerine/Oric Telestrat",
    "Tangerine Oric-1 & Oric Atmos" => "Tangerine/Oric-1 & Oric Atmos",
    "Tatung Einstein TC-01" => "Tatung/Einstein TC-01",
    "Technosys Aamber Pegasus" => "Technosys/Aamber Pegasus",
    "Tektronix 405x" => "Tektronix/405x",
    "Tektronix 4100 Series" => "Tektronix/4100 Series",
    "Tektronix 4400 Series" => "Tektronix/4400 Series",
    "Tektronix 8002" => "Tektronix/8002",
    "Telcon Zorba" => "Telcon/Zorba",
    "TeleNova Compis" => "TeleNova/Compis",
    "TeleVideo Systems TS-802 & TS-802H" => "TeleVideo Systems/TS-802 & TS-802H",
    "TeleVideo Systems TS-803, TS-803H & TPC-1" => "TeleVideo Systems/TS-803, TS-803H & TPC-1",
    "TeleVideo Systems TS-806" => "TeleVideo Systems/TS-806",
    "Telmac TMC-600" => "Telmac/TMC-600",
    "Terak 8510A & 8600" => "Terak/8510A & 8600",
    "Tesla Ondra Vili" => "Tesla/Ondra Vili",
    "Tesla PMD 85" => "Tesla/PMD 85",
    "Texas Instruments CC-40" => "Texas Instruments/CC-40",
    "Texas Instruments TI-73" => "Texas Instruments/TI-73",
    "Texas Instruments TI-74" => "Texas Instruments/TI-74",
    "Texas Instruments TI-80" => "Texas Instruments/TI-80",
    "Texas Instruments TI-81" => "Texas Instruments/TI-81",
    "Texas Instruments TI-82" => "Texas Instruments/TI-82",
    "Texas Instruments TI-83" => "Texas Instruments/TI-83",
    "Texas Instruments TI-85" => "Texas Instruments/TI-85",
    "Texas Instruments TI-86" => "Texas Instruments/TI-86",
    "Texas Instruments TI-89" => "Texas Instruments/TI-89",
    "Texas Instruments TI-92" => "Texas Instruments/TI-92",
    "Texas Instruments TI-95" => "Texas Instruments/TI-95",
    "Texas Instruments TI-99 4A" => "Texas Instruments/TI-99 4A",
    "The Byte Attic Agon" => "The Byte Attic/Agon",
    "The Byte Attic CERBERUS 2080" => "The Byte Attic/CERBERUS 2080",
    "Thomson MO5" => "Thomson/MO5",
    "Thomson MO6" => "Thomson/MO6",
    "Thomson TO7" => "Thomson/TO7",
    "Thomson TO8, TO8D, TO9, TO9+" => "Thomson/TO8, TO8D, TO9, TO9+",
    "Tiger Electronics Game.com" => "Tiger Electronics/Game.com",
    "Tiger Electronics K28 Talking Learning Computer" => "Tiger Electronics/K28 Talking Learning Computer",
    "Tiger Electronics Learning Computer" => "Tiger Electronics/Learning Computer",
    "Tiki Data Kontiki-100 & Tiki-100" => "Tiki Data/Kontiki-100 & Tiki-100",
    "TimeTop GameKing" => "TimeTop/GameKing",
    "TimeTop GameKing 3" => "TimeTop/GameKing 3",
    "Timex Sinclair TS-2068" => "Timex Sinclair/TS-2068",
    "Tomy Tutor & Pyuuta" => "Tomy/Tutor & Pyuuta",
    "Toshiba Pasopia" => "Toshiba/Pasopia",
    "Toshiba Pasopia 7" => "Toshiba/Pasopia 7",
    "Toshiba Visicom" => "Toshiba/Visicom",
    "Triumph-Adler Alphatronic PC" => "Triumph-Adler/Alphatronic PC",
    "Tsukuda Original Othello Multivision" => "Tsukuda Original/Othello Multivision",
    "UNIVAC Series 90" => "UNIVAC/Series 90",
    "USSR Vector-06C" => "USSR/Vector-06C",
    "University of Cambridge EDSAC" => "University of Cambridge/EDSAC",
    "University of Hawaii BCC 500" => "University of Hawaii/BCC 500",
    "University of Tokyo PC-1" => "University of Tokyo/PC-1",
    "VEB Mikroelektronik Erfurt Chess-Master Diamond" => "VEB Mikroelektronik Erfurt/Chess-Master Diamond",
    "VTech Genius" => "VTech/Genius",
    "VTech Genius Junior Movie" => "VTech/Genius Junior Movie",
    "VTech Genius Leader 2000" => "VTech/Genius Leader 2000",
    "VTech Genius Leader 6000SL" => "VTech/Genius Leader 6000SL",
    "VTech Genius Leader Color" => "VTech/Genius Leader Color",
    "VTech Laser 200" => "VTech/Laser 200",
    "VTech Laser 2001 & CreatiVision" => "VTech/Laser 2001 & CreatiVision",
    "VTech Laser 310" => "VTech/Laser 310",
    "VTech Laser 350, 500, 700 & 750" => "VTech/Laser 350, 500, 700 & 750",
    "VTech V.Smile" => "VTech/V.Smile",
    "VTech V.Smile Baby" => "VTech/V.Smile Baby",
    "VTech V.Smile Motion" => "VTech/V.Smile Motion",
    "Victor Technologies Victor 9000 & Sirius 1" => "Victor Technologies/Victor 9000 & Sirius 1",
    "Videoton TV-Computer" => "Videoton/TV-Computer",
    "Visual Technology VISUAL X Display Station" => "Visual Technology/VISUAL X Display Station",
    "Visual Technology Visual 1050" => "Visual Technology/Visual 1050",
    "Vtech Laser 3000 & Dick Smith CAT" => "VTech/Laser 3000 & Dick Smith CAT",
    "Wang 2200" => "Wang/2200",
    "Wang VS" => "Wang/VS",
    "Watara Supervision" => "Watara/Supervision",
    "Xerox 1108" => "Xerox/1108",
    "Xerox 1186" => "Xerox/1186",
    "Xerox 6085" => "Xerox/6085",
    "Xerox 820" => "Xerox/820",
    "Xerox 820-II" => "Xerox/820-II",
    "Xerox 860" => "Xerox/860",
    "Yamaha Copera" => "Yamaha/Copera",
    "Zilog MCZ-2" => "Zilog/MCZ-2",
};

/// Parse category from a TOSEC DAT filename
/// Returns the category path if the filename matches a known TOSEC pattern
pub fn parse_tosec_category(filename: &str) -> Option<String> {
    // Remove .dat extension
    let name = filename.strip_suffix(".dat").unwrap_or(filename);
    
    // Remove version suffix like "(TOSEC-v2024-07-03_CM)"
    let name = if let Some(idx) = name.rfind(" (TOSEC") {
        &name[..idx]
    } else if let Some(idx) = name.rfind("(TOSEC") {
        &name[..idx]
    } else {
        name
    };
    let name = name.trim();
    
    // Try to find the longest matching prefix
    let mut best_match: Option<(&str, &str)> = None;
    
    for (prefix, category) in TOSEC_PREFIX_MAP.entries() {
        if name.starts_with(*prefix) {
            // Check if this is a longer match than our current best
            if best_match.is_none_or(|(best_prefix, _)| prefix.len() > best_prefix.len()) {
                // Verify it's a complete prefix (followed by " - " or end of string)
                let rest = &name[prefix.len()..];
                if rest.is_empty() || rest.starts_with(" - ") {
                    best_match = Some((*prefix, *category));
                }
            }
        }
    }
    
    let (matched_prefix, category_prefix) = best_match?;
    
    // Parse the remaining suffix (e.g., " - Games - [ADF]" -> "/Games/[ADF]")
    let rest = &name[matched_prefix.len()..];
    if rest.is_empty() {
        return Some(category_prefix.to_string());
    }
    
    // Split on " - " and build category path
    let parts: Vec<&str> = rest.split(" - ")
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
        .collect();
    
    if parts.is_empty() {
        Some(category_prefix.to_string())
    } else {
        Some(format!("{}/{}", category_prefix, parts.join("/")))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_simple_category() {
        assert_eq!(
            parse_tosec_category("Commodore Amiga - Games - [ADF] (TOSEC-v2024-07-03_CM).dat"),
            Some("Commodore/Amiga/Games/[ADF]".to_string())
        );
    }

    #[test]
    fn test_multi_word_manufacturer() {
        assert_eq!(
            parse_tosec_category("Tandy Radio Shack TRS-80 Color Computer - Games - [CAS] (TOSEC-v2024).dat"),
            Some("Tandy Radio Shack/TRS-80 Color Computer/Games/[CAS]".to_string())
        );
    }

    #[test]
    fn test_no_format_suffix() {
        assert_eq!(
            parse_tosec_category("GCE Vectrex - Demos (TOSEC-v2023-08-29_CM).dat"),
            Some("GCE/Vectrex/Demos".to_string())
        );
    }

    #[test]
    fn test_unknown_prefix() {
        assert_eq!(
            parse_tosec_category("Unknown System - Games.dat"),
            None
        );
    }

    #[test]
    fn test_deep_category() {
        assert_eq!(
            parse_tosec_category("Acorn Archimedes - Collections - Skyfall Archimedes Public Domain - [ADF] (TOSEC-v2024-07-03_CM).dat"),
            Some("Acorn/Archimedes/Collections/Skyfall Archimedes Public Domain/[ADF]".to_string())
        );
    }
}

